-- Rollback: 0006_enable-rls-all-tables.sql
-- Reverses: Row-Level Security on all tables
-- NOTE: This disables RLS. Ensure no RLS policies depend on this before running.

ALTER TABLE households DISABLE ROW LEVEL SECURITY;
ALTER TABLE members DISABLE ROW LEVEL SECURITY;
ALTER TABLE pets DISABLE ROW LEVEL SECURITY;
ALTER TABLE pet_photos DISABLE ROW LEVEL SECURITY;
ALTER TABLE activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE invitations DISABLE ROW LEVEL SECURITY;
ALTER TABLE feeding_schedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE feeding_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE feeding_snoozes DISABLE ROW LEVEL SECURITY;
ALTER TABLE health_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE medications DISABLE ROW LEVEL SECURITY;
ALTER TABLE medication_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE medication_snoozes DISABLE ROW LEVEL SECURITY;
ALTER TABLE expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE pet_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE access_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE member_game_stats DISABLE ROW LEVEL SECURITY;
ALTER TABLE household_game_stats DISABLE ROW LEVEL SECURITY;
ALTER TABLE pet_game_stats DISABLE ROW LEVEL SECURITY;
ALTER TABLE activity_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE analytics_events DISABLE ROW LEVEL SECURITY;
